# Generated by Django 5.2.8 on 2025-11-12 23:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastillas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialToma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pastilla', models.CharField(max_length=100)),
                ('compartimento', models.IntegerField()),
                ('hora_programada', models.TimeField()),
                ('fecha_hora_real', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('TOMADA', 'Tomada'), ('OMITIDA', 'Omitida')], default='TOMADA', max_length=10)),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pastillas.tratamiento')),
            ],
            options={
                'verbose_name': 'Historial de Toma',
                'verbose_name_plural': 'Historial de Tomas',
                'ordering': ['-fecha_hora_real'],
            },
        ),
    ]
