# Generated by Django 5.0.7 on 2025-12-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastillas', '0002_historialtoma'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionArduino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_arduino', models.GenericIPAddressField(default='10.147.1.123')),
                ('puerto', models.IntegerField(default=80)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración Arduino',
                'verbose_name_plural': 'Configuración Arduino',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNotificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_activo', models.BooleanField(default=True)),
            ],
        ),
    ]
