# Generated by Django 5.0.7 on 2025-12-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastillas', '0003_configuracionarduino_configuracionnotificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionarduino',
            name='ip_arduino',
            field=models.GenericIPAddressField(default='10.147.1.1'),
        ),
    ]
